version: "3"
services:
  jenkins:
    container_name: "jenkins"
    image: "jenkins/jenkins:lts"
    ports: 
      - 8080:8080
      - 5050:50000
    volumes:
      - E:\SOP_Jenkins:/var/jenkins_home
  sonarqube:
    container_name: "sonarqube"
    image: "sonarqube"
    ports:
      - 9000:9000
   # environment: # Change these
      #- "sonar.jdbc.username=sonar" 
      #- "sonar.jdbc.password=sonar"
      #- "sonar.jdbc.url=jdbc:mysql://localhost"
    #
    volumes:
      - E:\SOP_Sonarqube\conf:/opt/sonarqube/conf
      - E:\SOP_Sonarqube\data:/opt/sonarqube/data
      - E:\SOP_Sonarqube\extentions:/opt/sonarqube/extensions
#gitlab, junit, maven, jfrog artifactory