version: "3"
services:
  jenkins:
    build: .
    container_name: "jenkins"
    ports:
      - 8084:8080
      - 5050:5000
    volumes:
      - ./SOP_Jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  sonarqube:
    container_name: "sonarqube"
    image: "sonarqube"
    ports:
      - 9000:9000
    volumes:
      - ./SOP_Sonarqube/conf:/opt/sonarqube/conf
      - ./SOP_Sonarqube/data:/opt/sonarqube/data
      - ./SOP_Sonarqube/extentions:/opt/sonarqube/extensions
#gitlab, junit, maven, jfrog artifactory
