version: "3"
services:
  jenkins:
    container_name: "jenkins"
    image: "jenkins/jenkins:lts"
    ports:
      - 8084:8080
      - 5050:5000
    volumes:
      #- /var/run/docker.sock:/var/run/docker.sock
      - //var/run/docker.sock:/var/run/docker.sock
      - E:\SOP_Jenkins:/var/jenkins_home
  sonarqube:
    container_name: "sonarqube"
    image: "sonarqube"
    ports:
      - 9000:9000
    volumes:
      - E:\SOP_Sonarqube\conf:/opt/sonarqube/conf
      - E:\SOP_Sonarqube\data:/opt/sonarqube/data
      - E:\SOP_Sonarqube\extentions:/opt/sonarqube/extensions
#gitlab, junit, maven, jfrog artifactory
